### ISSUE TITLE
TrajectoryDuration.valueOf(int value) is not static

### ISSUE THREAD

**Issue by rzblue** [CrossTheRoadElec/Phoenix-frc-lib#21]
The `valueOf()` method that takes an integer representing a value in ms for `TrajectoryPoint.TrajectoryDuration` is not static, and is instead a member method of the enum.

**Comment by ozrien** [comment]
Agreed. See example for the workaround.

**Comment by ozrien** [comment]
Issue has been resolved.
https://github.com/CrossTheRoadElec/Phoenix-frc-lib/blob/master/java/src/com/ctre/phoenix/motion/TrajectoryPoint.java#L30
