### ISSUE TITLE
CCI interface: use enums

### ISSUE THREAD

**Issue by virtuald** [CrossTheRoadElec/Phoenix-frc-lib#24]
This will make it easier to figure out what the actual parameters are supposed to be. Usually it's easy to guess which enum belongs, but having it as part of the function signature would help me autogenerate the documentation.

**Comment by JCaporuscio** [comment]
We've started doing this with newer features.
If there are specific items you'd like to see changed, please file a new issue on our releases repo and we'll address it.
https://github.com/CrossTheRoadElec/Phoenix-Releases
