### ISSUE TITLE
getOutputCurrent() is in BaseMotorController but presumably not supported by SPX

### ISSUE THREAD

**Issue by ryegleason** [CrossTheRoadElec/Phoenix-frc-lib#26]
According to https://content.vexrobotics.com/vexpro/pdf/VictorSPX-InfoSheet-20171129.pdf, the Victor SPX can't measure current, but it still has the getOutputCurrent() method it inherits from BaseMotorController. This should probably be moved to TalonSRX.

**Comment by ozrien** [comment]
This is correct and I agree. In the meantime I expect the return is zero amps when used with the Victor SPX.

**Comment by aswerdlow935** [comment]
Yes, the return is zero.....only saw this after testing for days with the method only to later realize it was always returning zero. Should definitely be moved (or at the least have a warning put in for now).

**Comment by ozrien** [comment]
Depending on what you are trying to accomplish, you can poll the current via PDP.

**Comment by JCaporuscio** [comment]
This has been fixed since 5.8.0
