### ISSUE TITLE
Team Update 14 & Version 5.2.2

### ISSUE THREAD

**Issue by bdaroz** [CrossTheRoadElec/Phoenix-frc-lib#34]
Team Update 14 references a 5.2.2 version of the Phoenix library. When will that get posted here?

**Comment by ozrien** [comment]
5.2.2 Installer is available here...
http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources

**Comment by bdaroz** [comment]
Thank you - but when will the code be merged into this repo?

**Comment by JCaporuscio** [comment]
There were no functional or feature changes with 5.2.2, and no changes to frc-lib.  There was a rebuild of the CCI library that included a workaround for the issue described in the Team Update.

I've updated the repo to include this binary, but otherwise there's no change from 5.2.1.
