### ISSUE TITLE
Confusing set method

### ISSUE THREAD

**Issue by alexanderswerdlow** [CrossTheRoadElec/Phoenix-frc-lib#37]
The set method with the (ControlMode mode, double demand0, double demand1) parameters should either me marked as deprecated or removed as it can cause some confusion (certainly did for me) for someone attempting to use the new feedforward update that might simply try to input a demand1 without specifying a DemandType.

**Comment by JCaporuscio** [comment]
This function was deprecated prior to the 2019 season.
Closing the tracker since the public API repo is now up-to-date.

As a note, this function will likely be removed for the 2020 season.
