### ISSUE TITLE
CCI Config{Get,Set}Parameter and ParamEnum type mismatch

### ISSUE THREAD

**Issue by auscompgeek** [CrossTheRoadElec/Phoenix-frc-lib#47]
All the `ConfigGetParameter` and `ConfigSetParameter` CCI functions take an `int` for their `param` arguments:

https://github.com/CrossTheRoadElec/Phoenix-api/blob/f9bbdb14324c35f49b02d9790c955886e46ef096/libraries/driver/include/ctre/phoenix/CCI/CANifier_CCI.h#L52-L53
https://github.com/CrossTheRoadElec/Phoenix-api/blob/f9bbdb14324c35f49b02d9790c955886e46ef096/libraries/driver/include/ctre/phoenix/CCI/MotController_CCI.h#L119-L120
https://github.com/CrossTheRoadElec/Phoenix-api/blob/f9bbdb14324c35f49b02d9790c955886e46ef096/libraries/driver/include/ctre/phoenix/CCI/PigeonIMU_CCI.h#L40-L41

However, `ParamEnum` is declared as a `uint32_t`:

https://github.com/CrossTheRoadElec/Phoenix-api/blob/f9bbdb14324c35f49b02d9790c955886e46ef096/libraries/driver/include/ctre/phoenix/paramEnum.h#L10-L11

**Comment by JCaporuscio** [comment]
Closing as issue is old.
