### ISSUE TITLE
Open Sourcing the CCI Simulation Harness

### ISSUE THREAD

**Issue by JaciBrunning** [CrossTheRoadElec/Phoenix-frc-lib#59]
For simulation, it seems you provide a CCI harness for Windows 64-bit and (for some releases) Linux 64-bit.

Since WPI and other tools support simulation on macOS, might it be worth open-sourcing the simulation version of CCI in order to allow users to build it themselves?

**Comment by JCaporuscio** [comment]
Closing this issue since simulation has changed and we now publish binaries for macOS.
