### ISSUE TITLE
Infinite recursion in configGetSupplyCurrentLimit, configGetStatorCurrentLimit

### ISSUE THREAD

**Issue by wrall** [CrossTheRoadElec/Phoenix-frc-lib#67]
Please use the following templates when submitting bugs, requesting support, or suggesting new features.

# Support Request / Bug Reporting

Please include as much of the following information as possible when submitting a support request/bug.
This will help you get a more expedient resolution to your issue.

## [1] Describe your setup.

Falcon motors controlled using TalonFX.

## [2] List firmware versions for ALL CTRE devices and your Phoenix Installation.

Talon FX Firmware 20.1.0.0,
"CTRE-Phoenix", "version": "5.17.6",

## [3] What behavior are you expecting and why?

Attempting to get supply current limit information.

## [4] What behavior are you observing (and how is it different from your expected behavior above)?

Infinite recursion in TalonFX's one-argument configGetSupplyCurrentLimit function.  Should call the two-argument configGetSupplyCurrentLimit with default timeout but actually calls itself.  Same problem for configGetStatorCurrentLimit.

## [5] List the procedure to reproduce the issue.

Try to call configGetSupplyCurrentLimit().  It also appears that configGetStatorCurrentLimit() has the same problem.

**Comment by JCaporuscio** [comment]
This has been fixed in the latest (5.18.1) release.

https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/tag/v5.18.1.0
