### ISSUE TITLE
WPI_TalonFX cannot be slaved

### ISSUE THREAD

**Issue by qhdwight** [CrossTheRoadElec/Phoenix-frc-lib#68]
From our testing, we could not get a `WPI_TalonFX` to follow another `WPI_TalonFX`. The master would spin, but the slave would remain idle with amber lights on. The issue can be fixed by:
- Disabling motor safety (feature of the WPI class) via `setSafetyEnabled(false)`
- Using the `TalonFX` instead without WPILib compatability
Not sure if this is specific to our setup, or if it can be reproduced. This also affects the `frc-characterization` module since it uses `WPI_TalonFX`. Didn't work with our drive until I went into the generated java code and explicitly disabled motor safety. Then all worked nicely and all motors blinked green.
vendordep version: `5.18.1`
Falcon firmware version: `20.2.3.0`
WPILib version: `2020.2.2`

Also, the javadoc stub for the `WPI_TalonFX` class seems to be incorrect. It is currently:
```
/**
 * CTRE Talon SRX Motor Controller when used on CAN Bus.
 */
public class WPI_TalonFX extends TalonFX implements SpeedController, Sendable
```

**Comment by JCaporuscio** [comment]
Motor Safety requires explicit Set() calls periodically.

So for any WPI_ Phoenix motor controller you will need to either disable motor safety or call the follow() function periodically.
